name: Python package

on: [push]

jobs:
  list-tests:
      runs-on: ubuntu-22.04
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - uses: actions/checkout@v4
        - id: set-matrix
          run: echo "matrix=$((find tests -name '*_test.py'; find tests -name 'test_*.py') | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test:

    runs-on: ubuntu-latest
    needs: [list-tests]
    strategy:
      matrix:
        python-version: ["3.10"]
        test-file: ${{ fromJson(needs.list-tests.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Test with pytest
        run: |
          uv run pytest ${{ matrix.test-file }} || uv run pytest ${{ matrix.test-file }} --lf

  test-multiversion-fast:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        test-file: ["tests/python/test_dfa.py"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Test with pytest
        run: |
          uv run pytest ${{ matrix.test-file }} || uv run pytest ${{ matrix.test-file }} --lf

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Lint with ruff
        run: |
          uv run ruff check --exit-non-zero-on-fix neurosym tests
          uv run ruff format --check neurosym tests

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Check that the docs build
        run: |
          cd docs && uv run make html
