name: Python package

on: [push]

jobs:
  list-tests:
      runs-on: ubuntu-22.04
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - uses: actions/checkout@v4
        - id: set-matrix
          run: echo "matrix=$((find tests -name '*_test.py'; find tests -name 'test_*.py') | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  setup-python-3.10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload Python environment
        uses: actions/upload-artifact@v3
        with:
          name: python-3.10-env
          path: |
            ${{ env.PYTHONPATH }}
            ${{ env.PIP_CACHE_DIR }}

  setup-python-3.11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload Python environment
        uses: actions/upload-artifact@v3
        with:
          name: python-3.11-env
          path: |
            ${{ env.PYTHONPATH }}
            ${{ env.PIP_CACHE_DIR }}

  setup-python-3.12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload Python environment
        uses: actions/upload-artifact@v3
        with:
          name: python-3.12-env
          path: |
            ${{ env.PYTHONPATH }}
            ${{ env.PIP_CACHE_DIR }}

  setup-python-3.13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload Python environment
        uses: actions/upload-artifact@v3
        with:
          name: python-3.13-env
          path: |
            ${{ env.PYTHONPATH }}
            ${{ env.PIP_CACHE_DIR }}

  test:
    runs-on: ubuntu-latest
    needs: [list-tests, setup-python-3.10, setup-python-3.13]
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
        test-file: ${{ fromJson(needs.list-tests.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Download Python environment
        uses: actions/download-artifact@v3
        with:
          name: python-${{ matrix.python-version }}-env
          path: python-env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest ${{ matrix.test-file }} || pytest ${{ matrix.test-file }} --lf

  test-multiversion-fast:
    runs-on: ubuntu-latest
    needs: [setup-python-3.10, setup-python-3.11, setup-python-3.12, setup-python-3.13]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        test-file: ["tests/python/test_dfa.py"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Download Python environment
        uses: actions/download-artifact@v3
        with:
          name: python-${{ matrix.python-version }}-env
          path: python-env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest ${{ matrix.test-file }} || pytest ${{ matrix.test-file }} --lf

  lint:
    runs-on: ubuntu-latest
    needs: [setup-python-3.10, setup-python-3.11, setup-python-3.12]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download Python environment
        uses: actions/download-artifact@v3
        with:
          name: python-${{ matrix.python-version }}-env
          path: python-env
      - name: Install dependencies
        run: |
          pip install -r requirements.txt pylint==3.2.7 black==24.4.2 isort==5.13.2
      - name: Lint with pylint
        run: |
          pylint --rcfile=.pylintrc neurosym setup.py tests
          isort neurosym tests
          black neurosym tests
          bash -c '[ $(git status --porcelain --untracked-files=no | wc -c) -eq 0 ]  || (git status; git diff; exit 1)'
 
  check-docs:
    runs-on: ubuntu-latest
    needs: [setup-python-3.10]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Download Python environment
        uses: actions/download-artifact@v3
        with:
          name: python-3.10-env
          path: python-env
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check that the docs build
        run: |
          cd docs && make html
